POST http://localhost:15666/solr/techproducts/update
    ?wt=json
    &commit=true
Content-Type: application/json

{
    "add": {
        "doc": {
            "id": "{{$guid}}-id",
            "sku": "{{$guid}}-sku",
        "name":"Civilization VI",
        "description":"Originally created by legendary game designer Sid Meier, Civilization is a turn-based strategy game in which you attempt to build an empire to stand the test of time. Become Ruler of the World by establishing and leading a civilization from the Stone Age to the Information Age. Wage war, conduct diplomacy, advance your culture, and go head-to-head with history's greatest leaders as you attempt to build the greatest civilization the world has ever known.\n\nCivilization VI offers new ways to engage with your world: cities now physically expand across the map, active research in technology and culture unlocks new potential, and competing leaders will pursue their own agendas based on their historical traits as you race for one of five ways to achieve victory in the game.",
        "manu_str":["Firaxis"],
        "cat":["Games",
          "History",
          "Entertainment"],
        "color":"purple",
        "price":64.2,
        "popularity":9,
        "in_stock":true,
        "timestamp":"{{$datetime iso8601}}"
        }
    }
}

###

GET http://localhost:15666/solr/techproducts/select
    ?facet.field=cat
    &facet=true
    &fq=price%3A%5B0%20TO%208%5D
    &q=aliquam
    &rows=100
    &sort=price%20asc
    &start=0
    &wt=json

###

POST http://localhost:15666/solr/techproducts/update/extract
    ?literal.id=uploadedviarestapi
    &literal.sku=13371337
    &literal.name=Practical Frozen Hat
    &literal.manu_str=Pfannerstill, Labadie and Miller
    &literal.cat=Yolo
    &literal.color=gold
    &literal.price=10.42
    &literal.popularity=3
    &literal.in_stock=true
    &commit=true
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="myfile"; filename="Game_of_Thrones.pdf"
Content-Type: application/pdf

< ./Game_of_Thrones.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

// allowed fields and their defaults: https://solr.apache.org/guide/solr/latest/indexing-guide/fields.html
POST http://localhost:15666/solr/techproducts/schema
Content-Type: application/json

{
  "add-field": {
    "name": "sku",
    "type": "string",
    "required": true
  }
}

###

// Get schema definition of code through Schema API
GET http://localhost:15666/solr/techproducts/schema

###
